### ISSUE TITLE
一些更新項目

### ISSUE THREAD

**Issue by hsiaoyi0504** [NTUBEBEISU/2016-camp-site#6]
1.議程時間更新
耀登 楊副總 7/8 14:30-15:30
研華  范瑋益(James Fan)副理 7/8 13:00-14:00

2.加上耀登,研華logo

**Comment by candy02058912** [comment]
就先放名字 講題待定嗎

**Comment by hsiaoyi0504** [comment]
對,忘記還有這個

宣捷生技 高通量平台研究處  劉家宏資深處長
影像分析軟體於精準醫療之應用
105年7月8日（五） 10:50-11:50   演講5

**Comment by hsiaoyi0504** [comment]
[2016台大生醫電資營-議程 (1).docx](https://github.com/NTUBEBEISU/2016-camp-site/files/317671/2016.-.1.docx)
最新版的議程在這～
