### ISSUE TITLE
一些更新項目

### ISSUE THREAD

**Issue by hsiaoyi0504** [NTUBEBEISU/2016-camp-site#8]
- 研華講題: 研華智能醫院IoMT行動醫療物聯解決方案與全球案例分享
- 宣捷講者更新: (參考附件
  [Yi-Hung-Huang_EXP.docx](https://github.com/NTUBEBEISU/2016-camp-site/files/326010/Yi-Hung-Huang_EXP.docx)
  )
  ![13492921_1309972372349569_18213097_n](https://cloud.githubusercontent.com/assets/10943928/16236661/bae7f492-380b-11e6-8db2-e9a4f088d563.jpg)

**Comment by hsiaoyi0504** [comment]
- 所長講題:生物資訊與精準醫療 (剩下的那個演講時段)
- 耀登楊智惠講題: 個人化醫療評估
- 耀登楊智惠講者資料如附件
  [講師介紹.pdf](https://github.com/NTUBEBEISU/2016-camp-site/files/327548/default.pdf)

**Comment by candy02058912** [comment]
宣捷講者更新: 請問有講題嗎

**Comment by hsiaoyi0504** [comment]
講題沒有更改
影像分析軟體於精準醫療之應用
